<?php

declare(strict_types=1);

namespace App\Repositories\Enums;

enum ActionPageEventAccessEnum: string
{
  case ERROR = "ERROR";
  case LOADING = "LOADING";
  case VERSION = "VERSION";

    // platform
  case COOKIE_CONFIRME = "COOKIE_CONFIRME";
  case REGISTER_DISPOSITIVE = "REGISTER_DISPOSITIVE";
  case REGISTER_DISPOSITIVE_SESSION = "REGISTER_DISPOSITIVE_SESSION";
  case PLATFORM_GEOLOCATION_FAIL = "PLATFORM_GEOLOCATION_FAIL";
  case PLATFORM_GEOLOCATION_SUCCESS = "PLATFORM_GEOLOCATION_SUCCESS";

    // Store
  case STORE_BANNER_ACTION = "STORE_BANNER_ACTION";

    // show
  case SHOW_PHONE = "SHOW_PHONE";
  case SHOW_FACEBOOK = "SHOW_FACEBOOK";
  case SHOW_INSTAGRAM = "SHOW_INSTAGRAM";

    // product
  case PRODUCT_SEARCH = "PRODUCT_SEARCH";

    // redirect
  case REDIRECT_FACEBOOK = "REDIRECT_FACEBOOK";
  case REDIRECT_INSTAGRAM = "REDIRECT_INSTAGRAM";
  case REDIRECT_LINK_PHONE = "REDIRECT_LINK_PHONE";
  case REDIRECT_LINK_WHATSAPP = "REDIRECT_LINK_WHATSAPP";
  case REDIRECT_LINK_GOOGLEMAPS = "REDIRECT_LINK_GOOGLEMAPS";
  case REDIRECT_LINK_SPLIT_BOLET = "REDIRECT_LINK_SPLIT_BOLET";

    // Payment
  case PAYMENT_COPY_INFO_PIX = "PAYMENT_COPY_INFO_PIX";
  case PAYMENT_COPY_INFO_BOLETO = "PAYMENT_COPY_INFO_BOLETO";
  case PAYMENT_RELOAD_QRCODE_PIX = "PAYMENT_RELOAD_QRCODE_PIX";

    // indique-ganhe
  case INDIQUE_GANHE_COPY_INFO_LINK = "INDIQUE_GANHE_COPY_INFO_LINK";
}
